easy_admin:
    design:
        form_theme:
            - …
            # Nice(r) display of "name" and "description" on edit Setting page.
            - '@ItkDevConfig/easy_admin/form/setting.html.twig'

    entities:
        Setting:
            controller: ItkDev\ConfigBundle\Controller\SettingController
            class: ItkDev\ConfigBundle\Entity\Setting
            disabled_actions: [new, delete]
            list:
                fields:
                    # - property: section
                    - property: name
                    - property: description
                    # - property: type
                    # - property: formType
                    - property: value
                      label: Value
                      template: '@ItkDevConfig/easy_admin/Setting/display_value.html.twig'

            edit:
                fields:
                    - property: name
                      # Important: "name" must be disabled to not overwrite the name when saving a setting
                      type_options:
                          disabled: true
                    - property: value
                      # type_options:
                      #     Optionally, make "value" non-required
                      #     required: false
                      #     Optionally, hide the "Value" label
                      #     label: false
                    - property: description
                      # Important: "description" must be disabled to not overwrite the name when saving a setting
                      type_options:
                          disabled: true
